# .render.yaml
services:
  - type: web
    name: tpi-backend-newest
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production